stack: python 3.6

environment:
  matrix:
  - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
    PYTHON: "3.5"
    PYTHON: "3.6"
    PYTHON: "3.7"

build: off

install:
- pip install tox

test_script:
- tox -v -e py